version: '3.8'
services:
  n8n-laptop:
    image: n8nio/n8n
    ports:
      - "127.0.0.1:5679:5678"
    volumes:
      - ./n8n-data:/root/.n8n
    env_file:
      - ../configs/.env
    restart: on-failure:3
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://127.0.0.1:5678/healthz', r => process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))\""]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
  mem0:
    build:
      context: ../scripts
      dockerfile: ../docker/Dockerfile.mem0.dockerfile
    ports:
      - "127.0.0.1:7778:7777"
    env_file:
      - ../configs/.env
    restart: on-failure:3
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket,sys; s=socket.socket(); s.settimeout(2); s.connect(('127.0.0.1',7777)); s.close()\""]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s